{{- if .Values.agent.enabled -}}
{{- if .Values.os.linux -}}
{{- $cluster := .Values.cluster | required "missing cluster value" -}}
{{- $clusterName := $cluster.name | required "missing cluster.name value" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "retina.name" . }}-config
  namespace: {{ .Values.namespace }}
data:
  leader-election: {{ .Values.agent.leaderElection | quote }}
  cluster-name: {{ $clusterName }}
  {{- if .Values.hubble.enabled }}
  # Enable Hubble gRPC service.
  enable-hubble: {{ .Values.hubble.enabled | quote }}
  # UNIX domain socket for Hubble server to listen to.
  hubble-socket-path: {{ .Values.hubble.socketPath | quote }}
{{- if hasKey .Values.hubble "eventQueueSize" }}
  # Buffer size of the channel for Hubble to receive monitor events. If this field is not set,
  # the buffer size is set to the default monitor queue size.
  hubble-event-queue-size: {{ .Values.hubble.eventQueueSize | quote }}
{{- end }}
{{- if hasKey .Values.hubble "eventBufferCapacity" }}
  # Capacity of the buffer to store recent events.
  hubble-event-buffer-capacity: {{ .Values.hubble.eventBufferCapacity | quote }}
{{- end }}
{{- if .Values.hubble.metrics.enabled }}
  # Address to expose Hubble metrics (e.g. ":7070"). Metrics server will be disabled if this
  # field is not set.
  hubble-metrics-server: ":{{ .Values.hubble.metrics.port }}"
  # A space separated list of metrics to enable. See [0] for available metrics.
  #
  # https://github.com/cilium/hubble/blob/master/Documentation/metrics.md
  hubble-metrics: {{- range .Values.hubble.metrics.enabled }}
    {{.}}
{{- end }}
  enable-hubble-open-metrics: {{ .Values.hubble.metrics.enableOpenMetrics | quote }}
{{- end }}
{{- if .Values.hubble.redact }}
{{- if eq .Values.hubble.redact.enabled true }}
  # Enables hubble redact capabilities
  hubble-redact-enabled: "true"
{{- if .Values.hubble.redact.http }}
  # Enables redaction of the http URL query part in flows
  hubble-redact-http-urlquery: {{ .Values.hubble.redact.http.urlQuery | quote }}
  # Enables redaction of the http user info in flows
  hubble-redact-http-userinfo: {{ .Values.hubble.redact.http.userInfo | quote }}
{{- if .Values.hubble.redact.http.headers }}
{{- if .Values.hubble.redact.http.headers.allow }}
  # Redact all http headers that do not match this list
  hubble-redact-http-headers-allow: {{- range .Values.hubble.redact.http.headers.allow }}
    {{ . }}
{{- end }}
{{- end }}
{{- if .Values.hubble.redact.http.headers.deny }}
  # Redact all http headers that match this list
  hubble-redact-http-headers-deny: {{- range .Values.hubble.redact.http.headers.deny }}
    {{ . }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- if .Values.hubble.redact.kafka }}
  # Enables redaction of the Kafka API key part in flows
  hubble-redact-kafka-apikey: {{ .Values.hubble.redact.kafka.apiKey | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- if .Values.hubble.export }}
  hubble-export-file-max-size-mb: {{ .Values.hubble.export.fileMaxSizeMb | quote }}
  hubble-export-file-max-backups: {{ .Values.hubble.export.fileMaxBackups | quote }}
{{- if .Values.hubble.export.static.enabled }}
  hubble-export-file-path: {{ .Values.hubble.export.static.filePath | quote }}
  hubble-export-fieldmask: {{ .Values.hubble.export.static.fieldMask | join " " | quote }}
  hubble-export-allowlist: {{ .Values.hubble.export.static.allowList | join "," | quote }}
  hubble-export-denylist: {{ .Values.hubble.export.static.denyList | join "," | quote }}
{{- end }}
{{- if .Values.hubble.export.dynamic.enabled }}
  hubble-flowlogs-config-path: /flowlog-config/flowlogs.yaml
{{- end }}
{{- end }}
{{- if hasKey .Values.hubble "listenAddress" }}
  # An additional address for Hubble server to listen to (e.g. ":4244").
  hubble-listen-address: {{ .Values.hubble.listenAddress | quote }}
{{- if .Values.hubble.tls.enabled }}
  hubble-disable-tls: "false"
  hubble-tls-cert-file: /var/lib/cilium/tls/hubble/server.crt
  hubble-tls-key-file: /var/lib/cilium/tls/hubble/server.key
  hubble-tls-client-ca-files: /var/lib/cilium/tls/hubble/client-ca.crt
{{- else }}
  hubble-disable-tls: "true"
{{- end }}
{{- end }}
{{- if .Values.hubble.preferIpv6 }}
  hubble-prefer-ipv6: "true"
{{- end }}
{{- if (not (kindIs "invalid" .Values.hubble.skipUnknownCGroupIDs)) }}
  hubble-skip-unknown-cgroup-ids: {{ .Values.hubble.skipUnknownCGroupIDs | quote }}
{{- end }}
{{- end }}
  config.yaml: |-
    apiServer:
      host: {{ .Values.apiServer.host }}
      port: {{ .Values.retinaPort }}
    logLevel: {{ .Values.logLevel }}
    enabledPlugin: {{ .Values.enabledPlugin_linux }}
    metricsInterval: {{ .Values.metricsInterval }}
    metricsIntervalDuration: {{ .Values.metricsIntervalDuration }}
    enableTelemetry: {{ .Values.enableTelemetry }}
    enablePodLevel: {{ .Values.enablePodLevel }}
    enableConntrackMetrics: {{ .Values.enableConntrackMetrics }}
    remoteContext: {{ .Values.remoteContext }}
    enableAnnotations: {{ .Values.enableAnnotations }}
    bypassLookupIPOfInterest: {{ .Values.bypassLookupIPOfInterest }}
    dataAggregationLevel: {{ .Values.dataAggregationLevel }}
    monitorSockPath: {{ .Values.monitorSockPath }}
{{- end}}
---
{{- if .Values.os.windows}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "retina.name" . }}-config-win
  namespace: {{ .Values.namespace }}
data:
  config.yaml: |-
    apiServer:
      host: {{ .Values.apiServer.host }}
      port: {{ .Values.retinaPort }}
    logLevel: {{ .Values.logLevel }}
    enabledPlugin: {{ .Values.enabledPlugin_win }}
    metricsInterval: {{ .Values.metricsInterval }}
    metricsIntervalDuration: {{ .Values.metricsIntervalDuration }}
    enableTelemetry: {{ .Values.enableTelemetry }}
    enablePodLevel: {{ .Values.enablePodLevel }}
    remoteContext: {{ .Values.remoteContext }}
    bypassLookupIPOfInterest: {{ .Values.bypassLookupIPOfInterest }}
{{- end}}

{{- end}}
