version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "microsoft/retina"
    commit-message:
      prefix: "deps"
    labels: ["area/infra", "area/dependencies"]
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "microsoft/retina"
    commit-message:
      prefix: "deps"
    labels: ["area/infra", "area/dependencies"]
    open-pull-requests-limit: 10
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "microsoft/retina"
    commit-message:
      prefix: "deps"
    labels: ["lang/go", "area/dependencies"]
    ignore:
      - dependency-name: "github.com/inspektor-gadget/inspektor-gadget"
    open-pull-requests-limit: 10
  - package-ecosystem: "gomod"
    directory: "/hack/tools"
    schedule:
      interval: "daily"
    reviewers:
      - "microsoft/retina"
    commit-message:
      prefix: "deps"
    labels: ["lang/go", "area/infra", "area/dependencies"]
    open-pull-requests-limit: 10
