apiServer:
  host: "0.0.0.0"
  port: 10093
# Supported - debug, info, error, warn, panic, fatal.
logLevel: info
enabledPlugin: ["hnsstats"]
# Interval, in seconds, to scrape/publish metrics.
metricsIntervalDuration: "10s"
# used to export telemetry to AppInsights
telemetryEnabled: true
