---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.12.1
  name: metricsconfigurations.retina.io
spec:
  group: retina.io
  names:
    categories:
    - retina
    kind: MetricsConfiguration
    listKind: MetricsConfigurationList
    plural: metricsconfigurations
    singular: metricsconfiguration
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: MetricsConfiguration contains the specification for the retina
          plugin metrics
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Specification of the desired behavior of the RetinaMetrics.
              Can be omitted because this is for advanced metrics.
            properties:
              contextOptions:
                items:
                  description: MetricsContextOptions indicates the configuration for
                    retina plugin metrics
                  properties:
                    additionalLabels:
                      description: AdditionalContext represents the additional context
                        of the metrics collected Such as Direction (ingress/egress)
                      items:
                        type: string
                      type: array
                      x-kubernetes-list-type: set
                    destinationLabels:
                      description: DestinationLabels represents the destination context
                        of the metrics collected Such as IP, pod, port, workload (deployment/replicaset/statefulset/daemonset)
                      items:
                        type: string
                      type: array
                      x-kubernetes-list-type: set
                    metricName:
                      description: MetricName indicates the name of the metric
                      type: string
                    sourceLabels:
                      description: SourceLabels represents the source context of the
                        metrics collected Such as IP, pod, port
                      items:
                        type: string
                      type: array
                      x-kubernetes-list-type: set
                  required:
                  - metricName
                  type: object
                type: array
              namespaces:
                description: MetricsNamespaces indicates the namespaces to include
                  or exclude in metric collection
                properties:
                  exclude:
                    items:
                      type: string
                    type: array
                    x-kubernetes-list-type: set
                  include:
                    items:
                      type: string
                    type: array
                    x-kubernetes-list-type: set
                type: object
            required:
            - contextOptions
            - namespaces
            type: object
          status:
            properties:
              lastKnownSpec:
                description: Specification of the desired behavior of the RetinaMetrics.
                  Can be omitted because this is for advanced metrics.
                properties:
                  contextOptions:
                    items:
                      description: MetricsContextOptions indicates the configuration
                        for retina plugin metrics
                      properties:
                        additionalLabels:
                          description: AdditionalContext represents the additional
                            context of the metrics collected Such as Direction (ingress/egress)
                          items:
                            type: string
                          type: array
                          x-kubernetes-list-type: set
                        destinationLabels:
                          description: DestinationLabels represents the destination
                            context of the metrics collected Such as IP, pod, port,
                            workload (deployment/replicaset/statefulset/daemonset)
                          items:
                            type: string
                          type: array
                          x-kubernetes-list-type: set
                        metricName:
                          description: MetricName indicates the name of the metric
                          type: string
                        sourceLabels:
                          description: SourceLabels represents the source context
                            of the metrics collected Such as IP, pod, port
                          items:
                            type: string
                          type: array
                          x-kubernetes-list-type: set
                      required:
                      - metricName
                      type: object
                    type: array
                  namespaces:
                    description: MetricsNamespaces indicates the namespaces to include
                      or exclude in metric collection
                    properties:
                      exclude:
                        items:
                          type: string
                        type: array
                        x-kubernetes-list-type: set
                      include:
                        items:
                          type: string
                        type: array
                        x-kubernetes-list-type: set
                    type: object
                required:
                - contextOptions
                - namespaces
                type: object
              reason:
                type: string
              state:
                default: Initialized
                enum:
                - Initialized
                - Accepted
                - Errored
                - Warning
                type: string
            required:
            - reason
            - state
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
