apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: retina-agent
  namespace: {{ include "retina-rust.namespace" . }}
  labels:
    {{- include "retina-rust.agent.selectorLabels" . | nindent 4 }}
    {{- include "retina-rust.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "retina-rust.agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "retina-rust.agent.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.agent.metricsPort | quote }}
        prometheus.io/path: "/metrics"
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: retina-agent
          image: {{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag }}
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          args:
            - "--grpc-port={{ .Values.agent.grpcPort }}"
            - "--log-level={{ .Values.agent.logLevel }}"
            {{- if .Values.agent.podLevel }}
            - "--pod-level"
            {{- end }}
            - "--operator-addr={{ include "retina-rust.operator.addr" . }}"
            - "--metrics-port={{ .Values.agent.metricsPort }}"
          env:
            - name: AYA_LOGS
              value: {{ .Values.agent.ayaLogs | quote }}
          securityContext:
            privileged: true
          ports:
            - containerPort: {{ .Values.agent.grpcPort }}
              name: hubble
              protocol: TCP
            - containerPort: {{ .Values.agent.metricsPort }}
              name: retina
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: retina
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: retina
            initialDelaySeconds: 2
            periodSeconds: 3
            timeoutSeconds: 1
            failureThreshold: 3
          {{- with .Values.agent.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      tolerations:
        - operator: Exists
